// 构建期脚本：从 GitHub 公共数据集拉取各国真实指标 + 国旗 SVG，
// 合并输出 js/country-data.js 与 assets/flags/<iso>.svg（提交进仓库，运行时零外部依赖）。
// 运行：node tools/build-data.mjs
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const FLAG_DIR = join(ROOT, 'assets', 'flags')
mkdirSync(FLAG_DIR, { recursive: true })

const SRC = {
  mledoze: 'https://raw.githubusercontent.com/mledoze/countries/master/countries.json',
  owid: 'https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv',
  life: 'https://raw.githubusercontent.com/samayo/country-json/master/src/country-by-life-expectancy.json',
  flag: iso => `https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3/${iso.toLowerCase()}.svg`,
}

const norm = s => (s || '').toLowerCase().replace(/[^a-z]/g, '')

async function getText(url) {
  const r = await fetch(url)
  if (!r.ok) throw new Error(r.status + ' ' + url)
  return r.text()
}

// 我们项目里的 193 个 ISO2（从 countries.js 提取）
function ourIsos() {
  const txt = readFileSync(join(ROOT, 'js', 'countries.js'), 'utf8')
  const block = txt.slice(txt.indexOf('const RAW'), txt.indexOf('// 由 ISO2'))
  return [...block.matchAll(/\['([A-Z]{2})'/g)].map(m => m[1])
}

function parseCSV(text) {
  const lines = text.split('\n')
  const header = lines[0].split(',')
  const col = {}
  ;['iso_code', 'year', 'population', 'gdp', 'co2', 'co2_per_capita', 'energy_per_capita'].forEach(k => col[k] = header.indexOf(k))
  // iso3 -> { metric: {year, val} }
  const out = {}
  for (let i = 1; i < lines.length; i++) {
    const r = lines[i].split(',')
    const iso = r[col.iso_code]
    if (!iso || !/^[A-Z]{3}$/.test(iso)) continue
    const year = +r[col.year]
    const e = out[iso] || (out[iso] = {})
    for (const m of ['population', 'gdp', 'co2', 'co2_per_capita', 'energy_per_capita']) {
      const v = r[col[m]]
      if (v !== '' && v != null && !isNaN(+v)) {
        if (!e[m] || year > e[m].year) e[m] = { year, val: +v }
      }
    }
  }
  return out
}

async function main() {
  console.log('fetching datasets…')
  const [mledozeRaw, owidRaw, lifeRaw] = await Promise.all([
    getText(SRC.mledoze), getText(SRC.owid), getText(SRC.life),
  ])
  const mledoze = JSON.parse(mledozeRaw)
  const owid = parseCSV(owidRaw)
  const life = JSON.parse(lifeRaw)

  // 名称 -> 寿命
  const lifeByName = {}
  for (const e of life) if (e.country && e.expectancy) lifeByName[norm(e.country)] = +e.expectancy

  // cca2 -> mledoze 条目
  const byCca2 = {}
  for (const c of mledoze) if (c.cca2) byCca2[c.cca2] = c

  const isos = ourIsos()
  console.log('countries:', isos.length)
  const data = {}
  let flagOk = 0, flagMiss = 0

  // 并发拉国旗
  const queue = [...isos]
  async function worker() {
    while (queue.length) {
      const iso = queue.shift()
      try {
        const svg = await getText(SRC.flag(iso))
        writeFileSync(join(FLAG_DIR, iso + '.svg'), svg)
        flagOk++
      } catch { flagMiss++; console.warn('flag miss', iso) }
    }
  }
  await Promise.all(Array.from({ length: 12 }, worker))
  console.log('flags:', flagOk, 'ok,', flagMiss, 'missing')

  for (const iso of isos) {
    const m = byCca2[iso] || {}
    const o = owid[m.cca3] || {}
    const common = m.name?.common || iso
    const population = o.population?.val ?? m.population ?? null
    const gdp = o.gdp?.val ?? null
    const co2 = o.co2?.val ?? null
    const co2PerCapita = o.co2_per_capita?.val ?? null
    const energy = o.energy_per_capita?.val ?? null
    const lifeExp = lifeByName[norm(common)] ?? lifeByName[norm(m.name?.official)] ?? null
    const cur = m.currencies ? Object.entries(m.currencies)[0] : null
    data[iso] = {
      name: common,
      population,
      gdp,                                   // 美元（当年）
      gdpPerCapita: gdp && population ? Math.round(gdp / population) : null,
      co2,                                   // 百万吨
      co2PerCapita,                          // 吨/人
      lifeExp,
      energyPerCapita: energy,
      area: m.area ?? null,                  // km²
      density: m.area && population ? +(population / m.area).toFixed(1) : null,
      region: m.region ?? null,
      subregion: m.subregion ?? null,
      capital: m.capital?.[0] ?? null,
      currency: cur ? `${cur[0]} (${cur[1].name})` : null,
      languages: m.languages ? Object.values(m.languages).join(', ') : null,
      latlng: m.latlng ?? null,
    }
  }

  const out = '// AUTO-GENERATED by tools/build-data.mjs — do not edit by hand.\n' +
    '// Sources: mledoze/countries (CC0/ODbL), owid/co2-data (CC-BY), samayo/country-json.\n' +
    'export const COUNTRY_DATA = ' + JSON.stringify(data, null, 0) + '\n'
  writeFileSync(join(ROOT, 'js', 'country-data.js'), out)
  console.log('wrote js/country-data.js (' + out.length + ' bytes)')

  // 简单覆盖率报告
  const have = k => isos.filter(i => data[i][k] != null).length
  for (const k of ['population', 'gdp', 'co2', 'lifeExp', 'area', 'capital'])
    console.log('  ', k, have(k) + '/' + isos.length)
}
main().catch(e => { console.error(e); process.exit(1) })
